### ISSUE TITLE
Fix project group assignment

### ISSUE THREAD

**Issue by nickjer** [OSC/osc-vnc#19]
Currently it just searches for the first group in the user's group list that starts with `P`. This has issues for internal staff that have a primary group like `appl` and add themselves to an external project for debugging purposes. All future VNC sessions will be charged against this external project.

The solution is to only check if the primary group starts with `P`. If the user is in a dual project scenario and the primary group doesn't start with a `P` then it should be the app's responsibility to decide and assign a project account.

**Comment by ericfranz** [comment]
>Currently it just searches for the first group in the user's group list that starts with P

What code does this? osc-machete does what you specify in the second paragraph:

>The solution is to only check if the primary group starts with P. If the user is in a dual project scenario and the primary group doesn't start with a P then it should be the app's responsibility to decide and assign a project account.

**Comment by nickjer** [comment]
>What code does this?

https://github.com/OSC/osc-vnc/blob/354b13656371d0ad7e6a3df56ac8331fcf3cf1c1/lib/osc/vnc/session.rb#L67-L69

**Comment by nickjer** [comment]
There are a few solutions for this:

1. I hard code in the internal OSC group to project mapping and default to using primary group for project
2. I do something similar to what `osc-machete` and default to using the primary group for project if it starts with `P` (but this will break VNCSim for some users, see issue https://github.com/AweSim-OSC/vncsim/issues/96)
3. I remove manipulation of the account name altogether, and if a user is in dual projects then they will see the `qsub` error. This can then be resolved by the user themself according to https://github.com/AweSim-OSC/vncsim/issues/96.

I lean towards option 3 because this is what dual project users already experience from the command line. As we aren't making assumptions about the project, the user will not experience any surprises.

**Comment by ericfranz** [comment]
I wonder how many users have multiple projects. Also, does the qsub error:

1. display to the user?
2. include a listing of all the projects they are part of?

**Comment by ericfranz** [comment]
I know the error on the command line does, but to clarify, the question is if this displays to the user.

**Comment by nickjer** [comment]
The command line error is displayed in the alert box at the top. Although we will definitely need to put it inside `<pre>` tags to clean up the display of it.

**Comment by nickjer** [comment]
Oh wait, I could be wrong about that last statement. I am thinking of the VFT web app. The VNCSim app has terrible error handling. This would need to be addressed if we go with option 3.

**Comment by nickjer** [comment]
Fixed in 044a0d7813e2bdf0fba8f96048181ce1b4ff4ab4
